name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Tous les jours à 00:00 UTC
  workflow_dispatch:       # Lancer manuellement si tu veux
  push:
    branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Autorise le push vers la branche de sortie
    steps:
      - name: Generate SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: francoismignon
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publie les fichiers générés dans la branche "output"
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
